spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: rental